[build]
builder = "nixpacks"
buildCommand = "npm install"
installCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/documents"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 